### ISSUE TITLE
Looks the module is missing from npm

### ISSUE THREAD

**Issue by jabejaranoq** [zbest1000/node-red-contrib-environmental-data-simulator#1]
Hello.

I tried to install the module but looks like it is missing from npm.  I got this error in the install log file>

not found
package 'node-red-contrib-environmental-data-simulator' not found

46 verbose stack node-red-contrib-environmental-data-simulator: No versions available for node-red-contrib-environmental-data-simulator
46 verbose stack     at pickManifest (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:140:25)
46 verbose stack     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:187:16)
46 verbose stack     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:119:22)
46 verbose stack     at async [nodeFromEdge] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1059:19)
46 verbose stack     at async [buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:929:11)
46 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
46 verbose stack     at async Promise.all (index 1)
46 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
46 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:147:5)
46 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:89:5)

Also got this message in the NPM page of the module:

not found
package 'node-red-contrib-environmental-data-simulator' not found

Is it possible to get the .tgz file directly from you?

Thanks in advanced.

**Comment by zbest1000** [comment]
Hello,

Thank you for reaching out about this. I actually removed the package from
npm. I’ve been working on upgrading the whole thing, it had a glitch so i
took it down for now. But here’s the the GitHub repo with some additional
features . You can clone this repo for your usage. Let me know if you have
any questions.

https://github.com/zbest1000/Node-Red-sensor-Data-Generators

**Comment by jabejaranoq** [comment]
Oh, I see!  Thank you!

**Comment by zbest1000** [comment]
Your welcome, please let me know if it works for you. I’m IoT based so my
knowledge of npm is not that great. If your interested or know someone who
is interested in maintaining the npm package with me please let me know.
Test out out the two subflow nodes and let me know what you think. The
manufacturing data generator is pretty interesting if you use a dashboard
graph to visualize the data.
